### ISSUE TITLE
IPTV TAMIL -Opens automatically in VLC player 

### ISSUE THREAD

**Issue by schwarzennegger-uk** [prabhacap/IPTV#1]
Hello Prabha,

First thank you so much for this , when i open the file in VLC as you said, it shows the list of channel but before trying to choose which channel to play, it starts playing AUSTRALIAN TAMIL channel which first on the list ! tried multiple times ,what i am doing wrong?

Thank you,
Surya

**Comment by prabhacap** [comment]
You need to change the channels that you want to watch!
